### ISSUE TITLE
connect using python socketio client

### ISSUE THREAD

**Issue by joasiee** [tradetosser/Trade-Tosser-Sockets#1]
Is the use of the nodejs client mandatory?

I have the following code:

```
import socketio

sio = socketio.Client()

@sio.event
def connect():
    print('Connected to tradetosser socket.')

@sio.event
def disconnect():
    print('Disconnected from socket.')


sio.connect('https://tradetosser.com:5000?token=<apiToken>')
sio.wait()
```

When i run it, nothing happens. Nothing is printed to the console. But the code does keep running indefinitely. Am i doing something wrong or does is the python socketio library not compatible?

**Comment by georgewhyte** [comment]
@joasiee did you get it working?

**Comment by tradetosser** [comment]
It's working now, let us know if you have any problems with it.
