### ISSUE TITLE
Can you connect to the trade-tosser sockets using python socket-io?

### ISSUE THREAD

**Issue by georgewhyte** [tradetosser/Trade-Tosser-Sockets#2]
I am new to sockets so I could be doing something wrong but please help.

```
import socketio

sio = socketio.Client()
sio.connect("https://tradetosser.com:5000?token=YOUR_API_KEY")
#sio.wait()

@sio.event
def connect():
    print('Connected to tradetosser socket.')

@sio.event
def disconnect():
    print('Disconnected from socket.')

print(sio.sid)
```

The only thing printed was the sid

**Comment by tradetosser** [comment]
Hi there, your code is good.
We're fixing a problem we had a problem with the API Key using python [I'll update it here when it goes live]

Also to access the pairs you can do this: 

> @sio.on('EURUSD')
> def on_message(data):
>     print(data)

**Comment by georgewhyte** [comment]
Okay thank you @tradetosser, it's working perfectly now!

**Comment by davekim917** [comment]
This is giving me "ConnectionError: Connection refused by the server" error, can you please advise?

**Comment by tradetosser** [comment]
Can you mail me at pedro@macrohedged.com so we run some tests?

**Comment by davekim917** [comment]
Sent you an email to that email address. Attached is the error I'm getting.
